### PR TITLE
Added hook for SetEnhancedConduit

### PR DESCRIPTION
**Pull request by hobulian**
Added hooksecurefunc(tip, "SetEnhancedConduit",SetConduit_Hook)
So it now can track conduits in soulbind tree

### CODE REVIEW

**Comment by frozn** [comment]
I haven't unlocked enhanced conduits yet, therefore I haven't been able to implement/test this... :scream:
I'm on here...

With regard to the keystones, I would add the following, too:
- Option to add affix descriptions from `C_ChallengeMode.GetAffixInfo(affixID)`
- Option to add weekly/end-of-run reward level from `C_MythicPlus.GetRewardLevelForDifficultyLevel(mythicLevel)`

**Comment by hobulian** [comment]
Wow. it's far more than i thought.
Will be really nice if those features added !

**Comment by hobulian** [comment]
> I haven't unlocked enhanced conduits yet, therefore I haven't been able to implement/test this... 😱 I'm on here...

I Added and checked this one. And it worked for sure.

**Comment by frozn** [comment]
I really want to implement these points.

**Comment by hobulian** [comment]
> I really want to implement these points.

Oh I moved this one to Issue tab so I closed this one kk

**Comment by frozn** [comment]
I added the following changes regarding keystones:

- added mouseover for dungeon score chatlink
- added class color to dungeon score tooltip
- added border color, icon and infos to keystones

Infos includes RewardLevel, WeeklyRewardLevel, ItemID, TimeLimit and AffixInfos.

Seems fine to me. What do you think?

**Comment by frozn** [comment]
`C_ChallengeMode.GetAffixInfo(affixID)` should return a localized description for the affixes. On my side it's working. :thinking:

**Comment by hobulian** [comment]
What i meant was like Weekly Reward Level to “주간 보상 레벨” 
C_ChallengeMode.GetAffixInfo(affixID) is working with translated phrase now and it’s fine i think.

**Comment by frozn** [comment]
I added the option "ItemRef->Modify Keystone Tooltips". Unfortunately you can't wrap the affix infos at that position, so the tooltip becomes significantly wider.

So far, localization has not been considered at all. Maybe a separate "nice to have" feature request should be created for this.

**Comment by hobulian** [comment]
Checked updated one. Think it feels much clear and short than before. What a improvement.

Hmm how about just overlapping default modifier name with fixed one like

local textRight = _G[tipName.."TextLeft"..(beginOfAffixes + i)];
							local newitt = "|T"..fileDataID..":0|t "..modifierName.."\n|cff3399ff"..modifierDescription;
			
							textRight:SetText(newitt) --(infoColorMixin:WrapTextInColorCode(format("%s", modifierDescription)));
							textRight:Show();

just example.

**Comment by frozn** [comment]
Nice suggestion including the icon. I committed my (final) change to main-branch. I moved the affix infos to the bottom of the tooltip, because it's visually cleaner in my opinion.

Everythings fine to close this issue? 😄

**Comment by hobulian** [comment]
Yeah. It looks neat and clean.

**Comment by frozn** [comment]
Localization follow up: #34

**Pull request closed without merging**
